# Generated by Django 4.2.6 on 2023-10-31 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_author_blog_created_at_alter_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='ism')),
                ('lastname', models.CharField(max_length=255, verbose_name='familiya')),
                ('age', models.PositiveSmallIntegerField(verbose_name='yosh')),
            ],
            options={
                'verbose_name': 'ega',
                'verbose_name_plural': 'egalar',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('id',), 'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
        migrations.AlterModelOptions(
            name='blogcategories',
            options={'ordering': ('id',), 'verbose_name': 'Blog kategoriyasi', 'verbose_name_plural': 'Bloglar kategoriyalari'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
