# Generated by Django 4.2.6 on 2023-11-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_author_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('create', 'yaratilgan'), ('accepted', 'tasdiqlangan'), ('cancelled', 'bekor qilingan')], default='created', max_length=50),
        ),
    ]
