# Generated by Django 4.2.6 on 2023-11-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='ism')),
                ('lastname', models.CharField(max_length=255, verbose_name='familiya')),
                ('age', models.PositiveSmallIntegerField(verbose_name='yosh')),
                ('seria', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'ega', 'verbose_name_plural': 'egalar'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.RemoveField(
            model_name='author',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lastname',
        ),
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('super admin', 'Bosh admin')], default='manager', max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.passportinfo', verbose_name='Passport malumotlari'),
        ),
    ]
